name: Bug Report
description: Report something that isn't working as expected
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this. Please fill out the sections below so we can reproduce and fix the issue.

  - type: dropdown
    id: friction-class
    attributes:
      label: Friction Class
      description: How severe is this issue? (See FRICTION-SPEC.md for definitions)
      options:
        - "Class I - Catastrophic (data loss, crashes)"
        - "Class II - Severe (blocks core workflow)"
        - "Class III - Moderate (workaround exists)"
        - "Class IV - Minor (cosmetic/polish)"
        - "Class V - Enhancement (not a bug)"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Sovwren are you running?
      placeholder: "e.g., v0.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: backend
    attributes:
      label: LLM Backend
      description: Which backend were you using?
      options:
        - LM Studio
        - Ollama
        - Other
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      description: Which model was loaded?
      placeholder: "e.g., ministral-3-8b-reasoning-2512"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: checkboxes
    id: session-state
    attributes:
      label: Session State
      description: What state was the session in when the issue occurred?
      options:
        - label: Workshop mode
        - label: Sanctuary mode
        - label: Idle state active
        - label: Red lens
        - label: Purple lens

  - type: dropdown
    id: context-band
    attributes:
      label: Context Band
      description: What was the context load indicator showing?
      options:
        - "Low (empty moon)"
        - "Medium (quarter moon)"
        - "High (half moon)"
        - "Critical (full moon)"
        - "Don't know / Not visible"

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely
      placeholder: "Describe what went wrong..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
      placeholder: "Describe what you expected..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we trigger this bug?
      placeholder: |
        1. Start the IDE with...
        2. Switch to...
        3. Send message...
        4. Observe...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error messages
      description: Paste any relevant error messages or logs
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context that might help (screenshots, config, etc.)
